### ISSUE TITLE
Incorrect directory 

### ISSUE THREAD

**Issue by AudioVitamins** [formsy/formsy-material-ui#242]
I am getting a build error 

> ./node_modules/formsy-material-ui/lib/FormsyAutoComplete.js
> Module not found: Can't resolve 'formsy-react/src/utils' in '/app/front/node_modules/formsy-material-ui/lib'

formsy-material-ui/lib/FormsyAutoComplete.js
33. var _utils = require('formsy-react/src/utils');

should the correct path be changed to

 './utils'

or should this module be deleted now that MU has moved away from autocomplete?

**Comment by rojobuffalo** [comment]
I don't think it would be `./utils`, since this is pulling in utils from the formsy-react project, not this one (formsy-material-ui). But it might make more sense to be importing from `lib` rather than `src`. I can't think of a reason not to switch that to `formsy-react/lib/utils`, can you?

Just for the sake of completion, what versions of formsy-material-ui, formsy-react, and material-ui do you have in your project?

And do you have a link that shows where material-ui decided to drop the autoComplete component? I'm guessing it's for v1 because v0.20 still has it.

**Comment by JesseRWeigel** [comment]
I was able to get rid of this error by changing line 33 in formsy-material-ui/lib/FormsyAutoComplete.js from ```var _utils = require('formsy-react/src/utils');``` to ```var _utils = require('formsy-react/lib/utils');```

I am not using autocomplete, so I am not sure if this actually fixes anything or just gets rid of the error message.

**Comment by timothyallan** [comment]
Yep, modifying line 33 works for me too. Just remember to do it every time you have to nuke your node_modules folder 📆

**Comment by iDVB** [comment]
Has a contributer looked into this issue yet?

**Comment by DevJulianSalas** [comment]
I have faced the same error too. 

> ./node_modules/formsy-material-ui/lib/FormsyAutoComplete.js
Module not found: Can't resolve 'formsy-react/src/utils' in '/app/node_modules/formsy-material-ui/lib'


```
"dependencies": {
    "axios": "^0.18.0",
    "create-react-class": "^15.6.3",
    "formsy-material-ui": "^0.6.3",
    "formsy-react": "^1.1.4",
    "inline-style-prefixer": "^4.0.0",
    "lint": "^1.1.2",
    "material-ui": "^1.0.0-beta.34",
    "material-ui-icons": "^1.0.0-beta.17",
    "prop-types": "^15.6.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.1",
    "sockjs-client": "^1.1.4"
  },
```

**Comment by rkuykendall** [comment]
There was never a `setMuiComponentAndMaybeFocus` component in `formsy-react`. Mostly due to `Mui` referring to Material UI which is not something `formsy-react` is involved with. For now I have changed this to use the `setMuiComponentAndMaybeFocus` utility in utils, as every single other component does.

If any active MUI user has an opinion on if the Autocomplete Labs component should be removed or supported in future releases, your opinion would be appreciated.

If any of you are interested in working with Formsy and Material UI again please reach out, we are looking for contributors.
